### ISSUE TITLE
Question: did you try to package your project and check how it plays on consumer side?

### ISSUE THREAD

**Issue by dadhi** [Konard/T4GenericsExample#2]
First, thanks for the useful example. 
I was searching for the one working in .Core.

I have my own T4 (MS VS based) solution in https://github.com/dadhi/DryIoc/blob/master/src/DryIoc/Container.Generated.tt,
but it does not work in .Net Core, and randomly works at all.
The main problem is that I want to publish tt and ttinclude files to content-based nuget package, and find a multiple issues on the package consumer side, like wrong pathes, unable to load assemblies, etc. 

Did you try to package you project and check what's happening on the other side?

**Comment by konard** [comment]
Well, I didn't try to package that. I decided to translate my whole project from C# to C++ as the result of research. I`m developing [an automated translator](https://github.com/linksplatform/RegularExpressions.Transformer.CSharpToCpp) for that task.

**Comment by dadhi** [comment]
Ok, thanks.
